# Generated by Django 5.1.6 on 2025-03-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estate_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='agents/')),
                ('language', models.JSONField()),
                ('verifications', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('state', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_rate', models.JSONField()),
                ('featured', models.JSONField()),
                ('recommendation', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField()),
                ('address', models.TextField()),
                ('acre_price', models.IntegerField()),
                ('acre', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('road_width', models.IntegerField()),
                ('land_category', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('tehsil_name', models.CharField(max_length=100)),
                ('locations_link', models.URLField()),
                ('img', models.ImageField(upload_to='properties/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.agent')),
            ],
        ),
    ]
