# Generated by Django 5.1.6 on 2025-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldata',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='generaldata',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='generaldata',
            name='top_rate',
        ),
        migrations.AddField(
            model_name='generaldata',
            name='featured',
            field=models.ManyToManyField(related_name='featured_properties', to='api.property'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='recommendation',
            field=models.ManyToManyField(related_name='recommended_properties', to='api.property'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='top_rate',
            field=models.ManyToManyField(related_name='top_rated', to='api.property'),
        ),
    ]
