# Generated by Django 5.1.6 on 2025-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
