# Generated by Django 5.1.6 on 2025-03-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userdata_name_userdata_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="details",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_between_delhi",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="eligible_for_clu",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="property",
            name="land_facing",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="layout",
            field=models.ImageField(
                default="properties/auzC7uegAL4sn1cfSKP1_Cj3YoZB.jpg",
                upload_to="properties/",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="nearest_highways",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="price_range",
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="road_width_filter",
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="sale_or_lease",
            field=models.CharField(
                choices=[("sale", "Sale"), ("lease", "Lease")],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="size_range",
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="village_name",
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="zone",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="img",
            field=models.ImageField(
                default="agents/image2_resized.jpg", upload_to="agents/"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="img",
            field=models.ImageField(
                default="properties/auzC7uegAL4sn1cfSKP1_Cj3YoZB.jpg",
                upload_to="properties/",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="phone",
            field=models.CharField(default="Unknown", max_length=15),
        ),
    ]
