# Generated by Django 5.1.6 on 2025-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_agent_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="acre_price",
            field=models.FloatField(),
        ),
    ]
