# Generated by Django 5.1.6 on 2025-04-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_property_acre_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="price_range",
        ),
        migrations.RemoveField(
            model_name="property",
            name="road_width_filter",
        ),
        migrations.RemoveField(
            model_name="property",
            name="size_range",
        ),
        migrations.AddField(
            model_name="property",
            name="isvaild",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="money_unit",
            field=models.CharField(
                choices=[
                    ("thousand", "Thousand"),
                    ("lakh", "Lakh"),
                    ("crore", "Crore"),
                ],
                default="crore",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="subagent",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="unit_of_land",
            field=models.CharField(
                choices=[
                    ("acres", "Acres"),
                    ("square_feet", "Square Feet"),
                    ("gaj", "Gaj"),
                    ("square_meters", "Square Meters"),
                    ("yard", "Yard"),
                ],
                default="acres",
                max_length=20,
            ),
        ),
    ]
