# Generated by Django 5.1.6 on 2025-04-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_property_price_range_property_road_width_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("haryana", "Haryana"),
                    ("delhi", "Delhi"),
                    ("punjab", "Punjab"),
                    ("uttar_pradesh", "Uttar Pradesh"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("haryana", "Haryana"),
                    ("delhi", "Delhi"),
                    ("punjab", "Punjab"),
                    ("uttar_pradesh", "Uttar Pradesh"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
