# Generated by Django 5.1.6 on 2025-04-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_agent_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="price_range",
        ),
        migrations.RemoveField(
            model_name="property",
            name="road_width_filter",
        ),
        migrations.RemoveField(
            model_name="property",
            name="size_range",
        ),
        migrations.AddField(
            model_name="property",
            name="footter",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Haryana", "Haryana"),
                    ("Delhi", "Delhi"),
                    ("Punjab", "Punjab"),
                    ("Uttar Pradesh", "Uttar Pradesh"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="money_unit",
            field=models.CharField(
                choices=[
                    ("Thousand", "Thousand"),
                    ("Lakh", "Lakh"),
                    ("Crore", "Crore"),
                ],
                default="crore",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="unit_of_land",
            field=models.CharField(
                choices=[
                    ("Acres", "Acres"),
                    ("Square Feet", "Square Feet"),
                    ("Gaj", "Gaj"),
                    ("Square Meters", "Square Meters"),
                    ("Yard", "Yard"),
                ],
                default="acres",
                max_length=20,
            ),
        ),
    ]
